using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace LibUsbNative;

[JsonSourceGenerationOptions(WriteIndented = true)]
[JsonSerializable(typeof(UsbDeviceDescriptor))]
[JsonSerializable(typeof(UsbConfigDescriptor))]
[JsonSerializable(typeof(UsbInterface))]
[JsonSerializable(typeof(UsbInterfaceDescriptor))]
[JsonSerializable(typeof(UsbEndpointDescriptor))]
[JsonSerializable(typeof(UsbEndpointAddress))]
[JsonSerializable(typeof(UsbEndpointAttributes))]
[JsonSerializable(typeof(UsbConfigAttributes))] // Added
[JsonSerializable(typeof(IUsbDeviceDescriptor))]
[JsonSerializable(typeof(IUsbConfigDescriptor))]
[JsonSerializable(typeof(IUsbInterface))]
[JsonSerializable(typeof(IUsbInterfaceDescriptor))]
[JsonSerializable(typeof(IUsbEndpointDescriptor))]
[JsonSerializable(typeof(UsbConfigDescriptor[]))]
[JsonSerializable(typeof(UsbInterface[]))]
[JsonSerializable(typeof(UsbInterfaceDescriptor[]))]
[JsonSerializable(typeof(UsbEndpointDescriptor[]))]
[JsonSerializable(typeof(List<UsbConfigDescriptor>))]
[JsonSerializable(typeof(List<UsbInterfaceDescriptor>))]
[JsonSerializable(typeof(List<UsbEndpointDescriptor>))]
[JsonSerializable(typeof(IReadOnlyList<IUsbConfigDescriptor>))]
[JsonSerializable(typeof(IReadOnlyList<IUsbInterfaceDescriptor>))]
[JsonSerializable(typeof(IReadOnlyList<IUsbEndpointDescriptor>))]
[JsonSerializable(typeof(IEnumerable<IUsbConfigDescriptor>))]
[JsonSerializable(typeof(IEnumerable<IUsbInterfaceDescriptor>))]
[JsonSerializable(typeof(IEnumerable<IUsbEndpointDescriptor>))]
internal partial class UsbJsonContextIndented : JsonSerializerContext { }

[JsonSourceGenerationOptions(WriteIndented = false)]
[JsonSerializable(typeof(UsbDeviceDescriptor))]
[JsonSerializable(typeof(UsbConfigDescriptor))]
[JsonSerializable(typeof(UsbInterface))]
[JsonSerializable(typeof(UsbInterfaceDescriptor))]
[JsonSerializable(typeof(UsbEndpointDescriptor))]
[JsonSerializable(typeof(UsbEndpointAddress))]
[JsonSerializable(typeof(UsbEndpointAttributes))]
[JsonSerializable(typeof(UsbConfigAttributes))] // Added
[JsonSerializable(typeof(IUsbDeviceDescriptor))]
[JsonSerializable(typeof(IUsbConfigDescriptor))]
[JsonSerializable(typeof(IUsbInterface))]
[JsonSerializable(typeof(IUsbInterfaceDescriptor))]
[JsonSerializable(typeof(IUsbEndpointDescriptor))]
[JsonSerializable(typeof(UsbConfigDescriptor[]))]
[JsonSerializable(typeof(UsbInterface[]))]
[JsonSerializable(typeof(UsbInterfaceDescriptor[]))]
[JsonSerializable(typeof(UsbEndpointDescriptor[]))]
[JsonSerializable(typeof(List<UsbConfigDescriptor>))]
[JsonSerializable(typeof(List<UsbInterfaceDescriptor>))]
[JsonSerializable(typeof(List<UsbEndpointDescriptor>))]
[JsonSerializable(typeof(IReadOnlyList<IUsbConfigDescriptor>))]
[JsonSerializable(typeof(IReadOnlyList<IUsbInterfaceDescriptor>))]
[JsonSerializable(typeof(IReadOnlyList<IUsbEndpointDescriptor>))]
[JsonSerializable(typeof(IEnumerable<IUsbConfigDescriptor>))]
[JsonSerializable(typeof(IEnumerable<IUsbInterfaceDescriptor>))]
[JsonSerializable(typeof(IEnumerable<IUsbEndpointDescriptor>))]
internal partial class UsbJsonContextCompact : JsonSerializerContext { }
